/*********************/
/* WICHTIGE HINWEISE */
/*********************/

/**
 * [INFO]
 *
 * edwin/admin/update-3_1_1-3_1_2.php ausführen um Benutzerberechtigungen für
 * die neue Version korrekt zu aktualisieren.
 *
 * ModuleCustomText:
 * In allen Texten des Modules, in denen HTML verwendet wird, muss das Flag
 * CTHtml = 1 gesetzt werden.
 *
 * Validation:
 * Bei der Ueberpruefung von Fax, Telefon und Mobiltelefonnummern werden nun
 * auch Klammern erlaubt (Validation::isPhoneNumber). Es sollten manuell
 * angepasste Sprachvariablen oder Sprachvariablen fuer projektspezifische Erweiterungen die diese
 * Validierungsfunktion benutzen entsprechend angepasst werden.
 * Backend: lang.core.php::global_message_field_phone_error
 *          lang.ModuleFrontendUserManagement.php::fu_message_invalid_phone|fax|mobile
 * Frontend: lang.ContentItemLogin.php::c_login_message_invalid_phone|fax|mobile
 * Siehe auch Ticket 1370 fuer angepasste Dateien.
 *
 * Wenn MultimediaBibliothek (ContentItemMB, ModuleMultimediaSidebox) in Verwendung:
 * Im Template ContentItemMB_part.tpl werden jetzt zu jeder MB Box alle zugewiesenen
 * Kategorien ausgegeben, deshalb muss ab jetzt eine LOOP zur Ausgabe der Kategorien
 * verwendet werden. Folgende Variablen geben nur mehr einen Leerstring aus und muessen durch
 * die Loop ersetzt werden: c_mb_category_title, c_mb_category_url -> Loop categories{c_mb_position}
 * Im Template ModuleMultimediaSidebox.tpl gibt c_ms_category_title nun einen Leerstring aus und
 * muss durch die Loop categories{c_ms_position} ersetzt werden.
 *
 * ModuleNews: Erweiterung um Start / Enddatum für Anzeige von Newsbeiträgen.
 * Am Backend werden nun standardmäßig alle Felder ausgeblendet und müssen im
 * custom_config.css wieder eingeblendet werden.
 *
 * Wenn ContentItemVD bzw. ISSUU in Verwendung: Ab dieser Version werden die ISSUU relevanten
 * VD Konfigurationsvariablen durch globale Variablen ueberschrieben.
 * Siehe wiki.q2e.at/index.php/Config_Global#Issuu
 *
 * In Modulen ( z.B. Sidebox ) kann nun standardmäßig kein Download mehr
 * verlinkt werden, der nicht
 * - bereits im Inhalt verlinkt wurde
 * - oder "Download immer anzeigen, auch wenn dieser nicht verwendet wird"
 *   gesetzt wurde
 * Soll das Verhalten wieder den pre-3.1.2 Versionen entsprechen, dann muss
 * die Konfigurationsvariable $_CONFIG['m_modules_show_only_available_files'] = false;
 * gesetzt werden.
 *
 * [/INFO]
 */

/******************************************************************************/
/*   ModuleCustomText - Probleme bei Mischung von HTML und Plaintext Texten   */
/******************************************************************************/

ALTER TABLE mc_module_customtext
ADD CTHtml TINYINT NOT NULL DEFAULT '0' AFTER CTPosition;

/******************************************************************************/
/* Multimedia Bibliothek: Zuweisung von einer od. mehreren Kategorien im CI   */
/******************************************************************************/

ALTER TABLE mc_contentitem_mb
ADD MBCategories varchar(75) NOT NULL DEFAULT '0' COMMENT '0-ShowAll' AFTER MBText3;

/**************************************************************************************/
/* ModuleUserManagement - Zugriff auf Startseite alleine kann nicht gespeichert werden*/
/**************************************************************************************/

ALTER TABLE mc_user ADD UModuleRights TEXT NOT NULL AFTER UBlockedMessage;
ALTER TABLE mc_user_rights CHANGE UTree UScope
ENUM( 'main', 'footer', 'login', 'pages', 'siteindex', 'user' ) NULL DEFAULT NULL;
ALTER TABLE mc_user_rights CHANGE UPaths UPaths TEXT NOT NULL DEFAULT '';

/******************************************************************************/
/*           Dokumentenupload fuer das Modul Multimedia Bibliothek            */
/******************************************************************************/

CREATE TABLE mc_issuu_document (
  IDID int(11) NOT NULL AUTO_INCREMENT,
  IDDocumentId varchar(100) NOT NULL COMMENT 'Generated by Issuu',
  IDUsername varchar(255) NOT NULL,
  IDName varchar(50) NOT NULL COMMENT 'Must be unique (http://issuu.com/<IDUsername>/docs/<IDName>)',
  IDTitle varchar(100) NOT NULL,
  IDState varchar(1) NOT NULL COMMENT 'A-Active P-Processing F-Failure',
  IDErrorCode smallint NULL,
  IDCreateDateTime datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  FK_SID int(11) NOT NULL,
  PRIMARY KEY (IDID),
  UNIQUE KEY IDDocumentId_UN (IDDocumentId),
  UNIQUE KEY IDName_UN (IDName),
  KEY FK_SID (FK_SID)
) ENGINE=MyISAM;

ALTER TABLE mc_module_medialibrary
ADD FK_IDID int(11) NOT NULL DEFAULT 0 COMMENT 'Issuu document' AFTER MImageTitles,
ADD INDEX ( FK_IDID );

/******************************************************************************/
/*          Modul Multimedia Bibliothek: Kategorie-Mehrfachzuweisung          */
/******************************************************************************/

CREATE TABLE mc_module_medialibrary_category_assignment (
  FK_MID int(11) NOT NULL,
  FK_MCID int(11) NOT NULL,
  UNIQUE KEY FK_MID_FK_MCID (FK_MID,FK_MCID),
  KEY FK_MID (FK_MID),
  KEY FK_MCID (FK_MCID)
) ENGINE=MyISAM;

INSERT INTO mc_module_medialibrary_category_assignment( FK_MID, FK_MCID )
SELECT MID, FK_MCID FROM mc_module_medialibrary;

ALTER TABLE mc_module_medialibrary DROP FK_MCID;

/******************************************************************************/
/*          ModuleNews: Start- und Enddatum für Anzeige von News              */
/******************************************************************************/

ALTER TABLE mc_module_news
ADD NWStartDateTime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER NWText,
ADD NWEndDateTime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER NWStartDateTime;
